import { 
  Leaf, 
  Wrench, 
  Settings2, 
  Users, 
  Flame, 
  Recycle, 
  Mic2, 
  Building2 
} from "lucide-react";

export const blogCategories = [
  { id: "all", label: "All Posts" },
  { id: "technology", label: "Technology" },
  { id: "guides", label: "How-To Guides" },
  { id: "sustainability", label: "Sustainability" },
  { id: "news", label: "Company News" },
];

export const blogPosts = [
  {
    id: 1,
    slug: "how-modern-biogas-digesters-work",
    category: "technology",
    title: "How Modern Biogas Digesters Work",
    excerpt: "Understanding the science behind turning organic waste into clean, combustible gas for your home.",
    content: "Biogas technology is a remarkably simple yet powerful way to manage waste. At its core, a biogas digester is an airtight container where bacteria break down organic matter—such as cow dung, kitchen waste, or crop residues—in the absence of oxygen. This process, called anaerobic digestion, produces a gas composed mainly of methane and carbon dioxide. \n\nModern digesters, like the fixed-dome models we install, are designed to maintain optimal temperatures and pressure. As the waste decomposes, the gas rises to the top of the dome, where it is piped directly to your kitchen. The remaining slurry, now odorless and free of pathogens, is automatically pushed out into a collection tank, ready to be used as a potent organic fertilizer.",
    author: "Mary Mwami",
    date: "May 15, 2026",
    readTime: "5 min read",
    image: "/assets/biogas plant.jpeg",
    tags: ["Biogas", "Clean Energy", "Technology"],
  },
  {
    id: 2,
    slug: "maintaining-your-biogas-system",
    category: "guides",
    title: "Maintaining Your Biogas System: A Checklist",
    excerpt: "Simple daily and weekly steps to ensure your system continues to produce high-quality gas for years.",
    content: "A well-maintained biogas system can last for over 25 years. To ensure your system performs at its peak, follow this simple maintenance checklist:\n\n1. **Daily Feeding**: Consistency is key. Feed your digester a consistent mix of waste and water (usually 1:1 ratio). Avoid overloading it one day and leaving it empty the next.\n2. **Check for Leaks**: Periodically use soapy water on pipe joints to check for gas leaks. If you see bubbles, tighten the connection.\n3. **Slurry Management**: Ensure the overflow point is clear so the bio-slurry can flow out freely. This prevents pressure build-up that could damage the dome.\n4. **Keep it Warm**: Digesters work best in warm conditions. If you live in a colder area, ensure the dome is well-insulated with soil or a greenhouse structure.\n\nBy following these steps, you guarantee a steady flame and a healthy digester ecosystem.",
    author: "Technical Team",
    date: "May 10, 2026",
    readTime: "8 min read",
    image: "/assets/service-1.jpg",
    tags: ["Maintenance", "DIY", "Safety"],
  },
  {
    id: 3,
    slug: "environmental-impact-of-bio-slurry",
    category: "sustainability",
    title: "The Environmental Impact of Bio-Slurry",
    excerpt: "Why the liquid by-product of your digester is just as valuable as the gas it produces.",
    content: "While most people install biogas systems for the free cooking gas, the real 'gold' is often the bio-slurry. During the digestion process, the nutrients in the organic waste (Nitrogen, Phosphorus, and Potassium) are preserved and converted into a form that plants can easily absorb.\n\nUnlike raw manure, bio-slurry is liquid and can be applied directly to crops or mixed with irrigation water. It improves soil structure, increases water retention, and—most importantly—replaces expensive chemical fertilizers. Farmers using our systems have reported up to a 40% increase in crop yields, particularly with leafy greens like kale and spinach. By using slurry, you're not just saving money; you're building a truly circular and sustainable farm.",
    author: "Ronald Mwau",
    date: "May 02, 2026",
    readTime: "6 min read",
    image: "/assets/kale.jpeg",
    tags: ["Organic Farming", "Bio-Slurry", "Soil Health"],
  },
  {
    id: 4,
    slug: "hot-flame-biogas-expands-to-bomet",
    category: "news",
    title: "Hot Flame Biogas Expands to Bomet County",
    excerpt: "Celebrating our new regional office and first 10 installations in the South Rift region.",
    content: "We are thrilled to announce that Hot Flame Biogas has officially opened its doors in Bomet County! This expansion is part of our commitment to making clean energy accessible to every household in the South Rift region. \n\nIn our first month of operation in Bomet, we have already completed 10 successful installations for dairy farmers who were previously struggling with high wood-fuel costs. Our new local team, led by experienced technicians, will provide site assessments, construction, and training for residents. We look forward to transforming more lives and protecting the beautiful forests of Bomet through sustainable energy solutions.",
    author: "Mary Mwami",
    date: "April 20, 2026",
    readTime: "3 min read",
    image: "/assets/project-1.jpg",
    tags: ["Growth", "Community", "Milestones"],
  },
  {
    id: 5,
    slug: "fixed-dome-vs-floating-drum",
    category: "technology",
    title: "Fixed Dome vs. Floating Drum: Which is Right for You?",
    excerpt: "A comprehensive comparison of the two most popular digester designs in East Africa.",
    content: "Choosing the right biogas design is crucial for long-term success. The two most common designs are the Fixed Dome and the Floating Drum. \n\n**Fixed Dome**: Built underground using bricks and cement. It has no moving parts, making it extremely durable and long-lasting (20+ years). It is also space-efficient as the top can be used for other farm activities. This is our preferred design at Hot Flame Biogas due to its low maintenance.\n\n**Floating Drum**: Features a steel or fiberglass drum that rises and falls with gas production. While it provides a constant gas pressure, the metal drum is prone to rusting and requires frequent painting and eventual replacement. \n\nFor most Kenyan households and institutions, the durability and 'build-and-forget' nature of the Fixed Dome system makes it the superior choice for ROI.",
    author: "Technical Team",
    date: "April 12, 2026",
    readTime: "10 min read",
    image: "/assets/finished doom installed.png",
    tags: ["Design", "Comparison", "Efficiency"],
  },
  {
    id: 6,
    slug: "optimizing-feedstock-gas-output",
    category: "guides",
    title: "Optimizing Feedstock for Maximum Gas Output",
    excerpt: "What to put in (and keep out) of your digester for the best gas production rates.",
    content: "Not all waste is created equal when it comes to gas production. To get the most 'bang for your buck,' you need to understand your feedstock. \n\n**The Best Inputs**: Cow dung is the gold standard because it already contains the bacteria needed for digestion. Pig waste and poultry droppings are also high-energy but require more careful water mixing. Kitchen waste (fruit peels, leftover food) is excellent for a quick gas boost.\n\n**What to Avoid**: Never put plastic, glass, or chemicals (like bleach or detergents) into your digester, as these will kill the helpful bacteria. Also, avoid large amounts of citrus peels or highly acidic waste, which can drop the pH level and stop gas production. \n\nA balanced diet for your digester ensures a bright, blue flame every single day.",
    author: "Ronald Mwau",
    date: "March 28, 2026",
    readTime: "7 min read",
    image: "/assets/cowss.jpeg",
    tags: ["Feedstock", "Optimization", "Gas Production"],
  },
];
